### ISSUE TITLE
Attempt to Exit Without Specifying Epoch Fails w/ Error

### ISSUE THREAD

**Issue by metanull-operator** [wealdtech/ethdo#17]
Attempted to exit a validator from the Onyx network using a command of the following form:

`ETHDO_PASSPHRASE="XXXXXXXXXXXXXXX" ethdo validator exit --account "Wallet/Account"`

Got the following error:
```
panic: interface conversion: interface {} is nil, not uint64

goroutine 1 [running]:
github.com/wealdtech/ethdo/cmd.validatorExitHandleAccountInput(0x139ff80, 0xc000594120, 0x10eb1fe, 0x18, 0x0)
        /home/metanull/go/pkg/mod/github.com/wealdtech/ethdo@v1.4.19/cmd/validatorexit.go:116 +0xe86
github.com/wealdtech/ethdo/cmd.validatorExitHandleInput(0x0, 0x0, 0x11102af)
        /home/metanull/go/pkg/mod/github.com/wealdtech/ethdo@v1.4.19/cmd/validatorexit.go:65 +0x375
github.com/wealdtech/ethdo/cmd.glob..func14(0x1ca2c00, 0xc00000f340, 0x0, 0x2)
        /home/metanull/go/pkg/mod/github.com/wealdtech/ethdo@v1.4.19/cmd/validatorexit.go:52 +0x41
github.com/spf13/cobra.(*Command).execute(0x1ca2c00, 0xc00000f320, 0x2, 0x2, 0x1ca2c00, 0xc00000f320)
        /home/metanull/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1ca1c40, 0x46293a, 0x1cb39a0, 0xc000000180)
        /home/metanull/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/metanull/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/wealdtech/ethdo/cmd.Execute()
        /home/metanull/go/pkg/mod/github.com/wealdtech/ethdo@v1.4.19/cmd/root.go:138 +0x31
main.main()
        /home/metanull/go/pkg/mod/github.com/wealdtech/ethdo@v1.4.19/main.go:19 +0x20
```

However, after looking at the relevant ethdo code, I decided I could probably avoid the error by explicitly setting the epoch, and it worked. For example: 

`ETHDO_PASSPHRASE="XXXXXXXXXXXXXXX" ethdo validator exit --account "Wallet/Account" --epoch 9665`

Resulted in:

`Validator exit transaction sent`

**Comment by mcdee** [comment]
Thank you for reporting this.  This issue was due to a change in configuration parameter usage between different versions of the spec.  It should work fine with later versions of ethdo that have the updated parameter name.
