### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dong77** [wealdtech/ethdo#48]
## Command line
```
./ethdo validator credentials set --offline \
--mnemonic="indoor dish desk flag debris potato excuse depart ticket judge file exit" \
--withdrawal-address=0x95222290DD7278Aa3Ddd389Cc1E1d165CC4BAfe5 \
--debug --verbose
```

The offline-preparation.json file is valid and exists in the current directory. It's too large (contains all validators on the network) to attach.

## The Panic

```
offline-preparation.json found; loading chain state
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xdabbf5]

goroutine 1 [running]:
github.com/wealdtech/ethdo/cmd/validator/credentials/set.(*command).generateOperations(0xc00040cea0, {0x1396fb0, 0xc00013e000})
	/go/src/github.com/wealdtech/ethdo/cmd/validator/credentials/set/process.go:220 +0x35
github.com/wealdtech/ethdo/cmd/validator/credentials/set.(*command).process(0xc00040cea0, {0x1396fb0, 0xc00013e000})
	/go/src/github.com/wealdtech/ethdo/cmd/validator/credentials/set/process.go:58 +0x75
github.com/wealdtech/ethdo/cmd/validator/credentials/set.Run(0x1a75da0)
	/go/src/github.com/wealdtech/ethdo/cmd/validator/credentials/set/run.go:36 +0x65
github.com/wealdtech/ethdo/cmd.glob..func31(0x1a75da0, {0x1063fce, 0x5, 0x5})
	/go/src/github.com/wealdtech/ethdo/cmd/validatorcredentialsset.go:40 +0x1d
github.com/spf13/cobra.(*Command).execute(0x1a75da0, {0xc000148820, 0x5, 0x5})
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x1a794a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/wealdtech/ethdo/cmd.Execute()
	/go/src/github.com/wealdtech/ethdo/cmd/root.go:155 +0x25
main.main()
	/go/src/github.com/wealdtech/ethdo/main.go:19 +0x17
```

## OS
Ubuntu official docker image.

**Comment by mcdee** [comment]
Thank you for reporting this, it has been addressed in release 1.26.2 (now available).
