### ISSUE TITLE
Error when generating a raw deposit transactions

### ISSUE THREAD

**Issue by valo** [wealdtech/ethdo#6]
I am getting fatal SIGTRAP error when I try to generate the deposit transaction. Steps to reproduce:

```sh
docker run -it -v /data:/root/.config valo/ethdo wallet create --wallet=Validators --type="hd" --walletpassphrase=12345 --seed="alien chef acid jealous essay save blast giant west vehicle gospel source exhaust pluck choose mind swamp moral duty kit denial stay danger antenna"
docker run -it -v /data:/root/.config valo/ethdo account create --account=Validators/1 --walletpassphrase=12345 --passphrase=validator12345
docker run -it -v /data:/root/.config valo/ethdo wallet create --wallet=Withdraw --type="hd" --walletpassphrase=12345 --seed="mosquito alarm pig lumber spend eager click acoustic find they universe donor economy equal woman misery dress night sorry scorpion uncover logic coin express"
docker run -it -v /data:/root/.config valo/ethdo account create --account=Withdraw/Primary --walletpassphrase=12345 --passphrase=withdraw12345
docker run -it -v /data:/root/.config valo/ethdo validator depositdata --validatoraccount=Validators/1 --withdrawalaccount=Withdraw/Primary --depositvalue=32Ether --passphrase=validator12345
```

I get the following error:

```
fatal: morestack on g0
SIGTRAP: trace trap
PC=0x482cb2 m=3 sigcode=128

goroutine 0 [idle]:
runtime.abort()
	/usr/local/go/src/runtime/asm_amd64.s:859 +0x2
runtime.morestack()
	/usr/local/go/src/runtime/asm_amd64.s:416 +0x25

goroutine 1 [syscall]:
runtime.cgocall(0xdf1df0, 0xc0006494f0, 0xc0000391c0)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0006494c0 sp=0xc000649488 pc=0x42430b
github.com/herumi/bls-eth-go-binary/bls._Cfunc_blsSignHash(0xc000654000, 0xc000038fc0, 0xc0000391c0, 0x20, 0x0)
	_cgo_gotypes.go:836 +0x4d fp=0xc0006494f0 sp=0xc0006494c0 pc=0x6403ed
github.com/herumi/bls-eth-go-binary/bls.(*SecretKey).SignHash.func1(0xc000649590, 0xc000038fc0, 0xc000649578, 0xc000649580)
	/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20200508110836-07e8f416e478/bls/bls.go:641 +0xbf fp=0xc000649540 sp=0xc0006494f0 pc=0x645c9f
github.com/herumi/bls-eth-go-binary/bls.(*SecretKey).SignHash(0xc000038fc0, 0xc0000391c0, 0x20, 0x20, 0xc000654000)
	/go/pkg/mod/github.com/herumi/bls-eth-go-binary@v0.0.0-20200508110836-07e8f416e478/bls/bls.go:641 +0x62 fp=0xc000649570 sp=0xc000649540 pc=0x6440b2
github.com/wealdtech/go-eth2-types/v2.(*BLSPrivateKey).Sign(0xc000038fc0, 0xc0000391c0, 0x20, 0x20, 0x180, 0xc0000362d0)
	/go/pkg/mod/github.com/wealdtech/go-eth2-types/v2@v2.3.1/blsprivatekey.go:58 +0x4f fp=0xc0006495b0 sp=0xc000649570 pc=0x6720bf
github.com/wealdtech/go-eth2-wallet-hd/v2.(*account).Sign(0xc0006af8c0, 0xc0000391c0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/wealdtech/go-eth2-wallet-hd/v2@v2.0.4/account.go:227 +0x153 fp=0xc000649610 sp=0xc0006495b0 pc=0xdcb0a3
github.com/wealdtech/ethdo/cmd.sign(0x13811e0, 0xc0006af8c0, 0xc0000391c0, 0x20, 0x20, 0xc000036280, 0x4e, 0x0, 0x1a69740)
	/app/cmd/root.go:412 +0x160 fp=0xc0006496a0 sp=0xc000649610 pc=0xddfb00
github.com/wealdtech/ethdo/cmd.signRoot(0x13811e0, 0xc0006af8c0, 0xc3a0c022bb542389, 0xf3f4ff25c084fa0a, 0xb2c338893966704, 0x778106094e2c6fa9, 0xc0000388a0, 0x20, 0x20, 0x38, ...)
	/app/cmd/root.go:402 +0x2fb fp=0xc000649788 sp=0xc0006496a0 pc=0xddf7fb
github.com/wealdtech/ethdo/cmd.signStruct(0x13811e0, 0xc0006af8c0, 0xff4920, 0xc0000348c0, 0xc0000388a0, 0x20, 0x20, 0xc0000388a0, 0x20, 0x20, ...)
	/app/cmd/root.go:380 +0x1dc fp=0xc000649870 sp=0xc000649788 pc=0xddf43c
github.com/wealdtech/ethdo/cmd.glob..func13(0x1a77c40, 0xc00007ea00, 0x0, 0x5)
	/app/cmd/validatordepositdata.go:95 +0xb5a fp=0xc000649d68 sp=0xc000649870 pc=0xdeb81a
github.com/spf13/cobra.(*Command).execute(0x1a77c40, 0xc00007e9b0, 0x5, 0x5, 0x1a77c40, 0xc00007e9b0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d fp=0xc000649e40 sp=0xc000649d68 pc=0x5f388d
github.com/spf13/cobra.(*Command).ExecuteC(0x1a76f20, 0x4631ea, 0x1a88840, 0xc000000180)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349 fp=0xc000649f18 sp=0xc000649e40 pc=0x5f4569
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/wealdtech/ethdo/cmd.Execute()
	/app/cmd/root.go:157 +0x31 fp=0xc000649f78 sp=0xc000649f18 pc=0xddcaf1
main.main()
	/app/main.go:19 +0x20 fp=0xc000649f88 sp=0xc000649f78 pc=0xdf12d0
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x212 fp=0xc000649fe0 sp=0xc000649f88 pc=0x456882
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000649fe8 sp=0xc000649fe0 pc=0x4833a1

goroutine 6 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc00010a6f0)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/policy.go:80 +0x129

goroutine 7 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000074300)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/cache.go:299 +0xed
created by github.com/dgraph-io/ristretto.NewCache
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/cache.go:162 +0x22a

goroutine 8 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001a4810)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/policy.go:80 +0x129

goroutine 9 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000074480)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/cache.go:299 +0xed
created by github.com/dgraph-io/ristretto.NewCache
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/cache.go:162 +0x22a

goroutine 10 [select]:
github.com/dgraph-io/ristretto.(*defaultPolicy).processItems(0xc0001ea930)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/policy.go:96 +0xbe
created by github.com/dgraph-io/ristretto.newDefaultPolicy
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/policy.go:80 +0x129

goroutine 11 [select]:
github.com/dgraph-io/ristretto.(*Cache).processItems(0xc000074600)
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/cache.go:299 +0xed
created by github.com/dgraph-io/ristretto.NewCache
	/go/pkg/mod/github.com/dgraph-io/ristretto@v0.0.2/cache.go:162 +0x22a

rax    0x17
rbx    0xc00004e700
rcx    0x484e65
rdx    0x17
rdi    0x2
rsi    0x10d5a96
rbp    0x7f6701e34820
rsp    0x7f6701e31d90
r8     0x6c3125fc13e165d8
r9     0xd1d20fdf4ac0212c
r10    0xe7176e6ec60b0ac2
r11    0x212
r12    0x7f6701e35120
r13    0x7f6701e33620
r14    0x7f6701e34820
r15    0x7f6701e57868
rip    0x482cb2
rflags 0x216
cs     0x33
fs     0x0
gs     0x0
```

The error seems to happen from time to time, which is really weird. I am not sure how to isolate it even more.

**Comment by mcdee** [comment]
This appears to be an issue with the alpine image, see https://github.com/godror/godror/issues/30 for details

**Comment by valo** [comment]
Right. Seems like it will be a good idea to switch the base image to something else. Closing this. I'll update the PR with the Dockerfile to have a debian base image.
